name: apply_dart_fix
on: 
  workflow_dispatch:
defaults:
  run:
    working-directory: package
jobs:
  dart_fix_commit:
    name: Dart Fix and Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Dart
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: dart fix --apply
      - run: |
          git diff-index --quiet HEAD || git commit -am "Apply Dart fix"

