name: Deploy Flutter Web to GitHub Pages
permissions:
  contents: write
defaults:
  run:
    working-directory: package/example
on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.PAT}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web
        
      - name: deploy demo web app
      - run: |
          cd build/web
          git init
          git config --global user.email zezoh3358@gmail.com
          git config --global user.name Abdelaziz
          git status
          git remote add origin https://${{secrets.PAT}}github.com/zezo357/flutter_meedu_videoplayer_example
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin main -f

