name: Deploy Flutter Web to GitHub Pages

defaults:
  run:
    working-directory: package/example
on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.PAT}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web
        
      - name: Deploy demo web app
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          composer config --global github-oauth.github.com $PAT
          git clone https://github.com/zezo357/flutter_meedu_videoplayer_example.git
          git clone https://$PAT@github.com/zezo357/flutter_meedu_videoplayer_example.git
          cd build/web
          git init
          git config --global user.email zezoh3358@gmail.com
          git config --global user.name Abdelaziz
          git status
          git remote add origin https://github.com/zezo357/flutter_meedu_videoplayer_example.git
          git add --all
          git commit -m "update"
          git push origin HEAD:gh-pages

